import json
import asyncio
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import Optional
from langchain_core.messages import HumanMessage

from continum.orchestration import app_graph
from continum.state import AgentState

router = APIRouter(prefix="/api/chat", tags=["Chat & Copilot"])


class ChatRequest(BaseModel):
    message: str = Field(..., description="User message text")
    thread_id: str = Field("default_thread", description="Unique conversation thread ID")
    active_experiment_id: Optional[str] = Field(None, description="Currently selected experiment ID in MatchView Header")


@router.post("/stream")
async def chat_stream_endpoint(payload: ChatRequest):
    """
    Server-Sent Events (SSE) streaming endpoint for real-time conversation,
    tool status indicators, and generative UI card rendering.
    """
    config = {"configurable": {"thread_id": payload.thread_id}}
    
    initial_state = {
        "messages": [HumanMessage(content=payload.message)],
        "active_experiment_id": payload.active_experiment_id,
        "ui_artifacts": [],
        "errors": []
    }

    async def event_generator():
        # Stream events from the LangGraph orchestrator
        async for event in app_graph.astream_events(initial_state, config, version="v2"):
            kind = event["event"]

            # 1. Stream text token chunks from LLM
            if kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"].content
                if chunk:
                    yield f"data: {json.dumps({'type': 'text_token', 'content': chunk})}\n\n"

            # 2. Stream tool execution status
            elif kind == "on_tool_start":
                tool_name = event["name"]
                tool_display = tool_name.replace('_', ' ').title()
                yield f"data: {json.dumps({'type': 'tool_start', 'tool': tool_name, 'message': f'Executing {tool_display}...'})}\n\n"

            # 3. Stream completed UI artifacts generated by tools/subgraphs
            elif kind == "on_tool_end":
                tool_output = event["data"].get("output")
                if isinstance(tool_output, dict) and "ui_artifacts" in tool_output:
                    artifacts = tool_output["ui_artifacts"]
                    for art in artifacts:
                        # Convert Pydantic or dict artifact to JSON
                        art_dict = art.model_dump() if hasattr(art, "model_dump") else art
                        yield f"data: {json.dumps({'type': 'artifact', 'payload': art_dict})}\n\n"

        yield "data: [DONE]\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")