import operator
from datetime import datetime
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict

from pydantic import BaseModel, Field

# ==========================================
# 1. Enums & Literal Discriminators
# ==========================================

ExperimentStatus = Literal["DRAFT", "RUNNING", "PAUSED", "COMPLETED", "ARCHIVED"]
PhaseType = Literal["DISCOVERY", "PLANNING", "EXECUTION", "EVALUATION", "INSIGHTS"]
SRMStatusType = Literal["HEALTHY", "WARNING", "CRITICAL"]
ArtifactType = Literal[
    "stat_results_card",
    "srm_alert_card",
    "plotly_chart",
    "experiment_brief",
    "growth_prediction_card",
    "sql_result_card",
    "custom_card",
]


# ==========================================
# 2. MatchView UI Artifact Model
# ==========================================


class UIArtifact(BaseModel):
    """
    Structured visual artifact generated by tool execution and subgraphs.
    Sent over SSE to render dynamic interactive cards in MatchView workspace.
    """

    artifact_id: str = Field(..., description="Unique artifact identifier")
    type: ArtifactType = Field("stat_results_card", description="MatchView card component type")
    title: str = Field(..., description="Display title for the visual card")
    payload: Dict[str, Any] = Field(
        default_factory=dict, description="Component-specific JSON props"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(), description="Creation timestamp"
    )


# ==========================================
# 3. Card Payload Helper Schemas (Typed Component Props)
# ==========================================


class StatResultsPayload(BaseModel):
    control_mean: float
    treatment_mean: float
    relative_lift_pct: float
    p_value: float
    is_statistically_significant: bool
    confidence_interval: List[float]
    summary: str


class SRMAlertPayload(BaseModel):
    control_count: int
    treatment_count: int
    expected_ratio: float = 0.5
    p_value: float
    srm_detected: bool
    status: SRMStatusType
    summary: str


class PowerCalcPayload(BaseModel):
    sample_size_per_variant: int
    total_sample_size: int
    mde_relative: float
    baseline_rate: float
    estimated_days: int
    summary: str


class ExperimentBriefPayload(BaseModel):
    hypothesis: str
    primary_metric: str
    guardrail_metrics: List[str] = Field(default_factory=list)
    sample_size_per_variant: int
    target_lift_pct: float
    estimated_annual_impact: float


# ==========================================
# 4. Database Catalog & Introspection Models
# ==========================================


class ColumnDefinition(BaseModel):
    name: str
    data_type: str
    is_nullable: bool = True
    description: str = ""


class MetricDefinition(BaseModel):
    name: str
    table: str
    column: str
    aggregation: Literal["SUM", "AVG", "COUNT", "COUNT_DISTINCT", "MIN", "MAX"] = "AVG"
    description: str = ""


class TableSchema(BaseModel):
    table_name: str
    row_count: Optional[int] = None
    columns: List[ColumnDefinition] = Field(default_factory=list)


class SchemaMetadata(BaseModel):
    tables: List[str] = Field(default_factory=list)
    table_schemas: Dict[str, TableSchema] = Field(default_factory=dict)
    schema_summary: str = ""
    metrics_catalog: Dict[str, MetricDefinition] = Field(default_factory=dict)
    cataloged_experiments: List[Dict[str, Any]] = Field(default_factory=list)


# ==========================================
# 5. Project & Experiment Metadata Models
# ==========================================


class VariantConfig(BaseModel):
    name: str
    allocation_ratio: float = 0.5


class ExperimentSummary(BaseModel):
    project_id: str
    experiment_id: str
    name: str
    status: ExperimentStatus = "RUNNING"
    primary_metric: str
    sample_size: int = 0
    srm_status: SRMStatusType = "HEALTHY"
    table_source: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class ExperimentBrief(BaseModel):
    experiment_id: str
    hypothesis: str
    primary_metric: MetricDefinition
    guardrails: List[MetricDefinition] = Field(default_factory=list)
    target_mde: float
    baseline_rate: float
    required_sample_size: int
    traffic_split: Dict[str, float] = Field(
        default_factory=lambda: {"control": 0.5, "treatment": 0.5}
    )


# ==========================================
# 6. Tool Execution & Audit Logs
# ==========================================


class ToolExecutionRecord(BaseModel):
    tool_name: str
    input_params: Dict[str, Any]
    result: Optional[Dict[str, Any]] = None
    status: Literal["success", "failed"] = "success"
    error_message: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ==========================================
# 7. Human-in-the-Loop (HITL) Checkpoint State
# ==========================================


class PendingAction(BaseModel):
    action_type: str  # e.g., "EXECUTE_WRITE_SQL", "PUBLISH_EXPERIMENT"
    description: str
    payload: Dict[str, Any]
    requested_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ==========================================
# 8. Main AgentState & Subgraph States
# ==========================================


class AgentState(TypedDict):
    """
    Global LangGraph State container persisted across threads, tools, and HITL checkpoints.
    """

    messages: Annotated[List[Any], operator.add]
    active_project_id: Optional[str]
    active_experiment_id: Optional[str]
    domain_context: Optional[Literal["ecomm", "store"]]
    thread_id: str
    active_phase: PhaseType
    schema_metadata: Optional[SchemaMetadata]
    tool_executions: Annotated[List[ToolExecutionRecord], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]
    requires_approval: bool
    pending_action: Optional[PendingAction]


# Subgraph-Specific States
#
# Each subgraph carries (a) the inputs its domain functions genuinely require and
# (b) the results those functions returned, stored as `model_dump()` dicts — the
# same convention `orchestration/tools/adapter.py` uses when it builds UIArtifact
# payloads. Results are dicts rather than typed ExpSuite models on purpose: this
# module is imported BY `mapMeta`, so importing ExpSuite/mapMeta types back into
# it would create an import cycle.
#
# Required inputs are Optional here only because a graph may be invoked before
# the caller has supplied them. A node that finds one missing appends its name to
# `missing_inputs` and returns — it must never substitute a default. Fabricated
# statistics are the failure mode `19f8d33` fixed, and the supervisor prompt
# forbids them outright.


class IngestionState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    schema_metadata: Optional[SchemaMetadata]
    raw_tables_discovered: List[str]
    errors: Annotated[List[str], operator.add]


class PlanningState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: Optional[str]
    domain_context: Optional[Literal["ecomm", "store"]]
    experiment_brief: Optional[ExperimentBrief]
    # Inputs required by ExpSuite.planning — no defaults invented for these.
    baseline_rate: Optional[float]
    mde_relative: Optional[float]
    primary_metric: Optional[str]
    retail_domain: Optional[str]
    annual_traffic: Optional[int]
    average_order_value: Optional[float]
    assumed_relative_lift: Optional[float]
    daily_traffic: Optional[int]
    num_variants: Optional[int]
    control_split: Optional[float]
    # Results from calculate_power / calculate_opportunity_size /
    # plan_experiment_metrics / calculate_traffic_balance.
    power_result: Optional[Dict[str, Any]]
    opportunity_result: Optional[Dict[str, Any]]
    metric_plan_result: Optional[Dict[str, Any]]
    traffic_balance_result: Optional[Dict[str, Any]]
    missing_inputs: Annotated[List[str], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]


class MonitoringState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: str
    # Inputs required by ExpSuite.detect_srm.
    observed_counts: Optional[List[int]]
    expected_ratios: Optional[List[float]]
    # Live telemetry from mapMeta.fetch_statsig_experiment_health, dumped.
    telemetry: Optional[Dict[str, Any]]
    srm_result: Optional[Dict[str, Any]]
    srm_status: SRMStatusType
    guardrail_alerts: List[str]
    missing_inputs: Annotated[List[str], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]


class AnalysisState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: str
    domain_context: Optional[Literal["ecomm", "store"]]
    primary_metric: str
    use_cuped: bool
    # Inputs required by ExpSuite.calculate_hypothesis_test.
    control_mean: Optional[float]
    control_std: Optional[float]
    control_count: Optional[int]
    treatment_mean: Optional[float]
    treatment_std: Optional[float]
    treatment_count: Optional[int]
    alpha: Optional[float]
    # Optional pre-period covariates for ExpSuite.apply_cuped.
    y_control: Optional[List[float]]
    x_control: Optional[List[float]]
    y_treatment: Optional[List[float]]
    x_treatment: Optional[List[float]]
    # Optional pre/post means for ExpSuite.calculate_diff_in_diff.
    control_pre: Optional[float]
    control_post: Optional[float]
    treatment_pre: Optional[float]
    treatment_post: Optional[float]
    # Results.
    cuped_result: Optional[Dict[str, Any]]
    stat_result: Optional[Dict[str, Any]]
    causal_result: Optional[Dict[str, Any]]
    roi_summary: Optional[Dict[str, Any]]
    chart_spec: Optional[Dict[str, Any]]
    plotly_json: Optional[Dict[str, Any]]
    statistical_significance: Optional[bool]
    missing_inputs: Annotated[List[str], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]


class AskDataState(TypedDict):
    """
    Backs three independent entry points rather than one fixed chain: SQL,
    visualization, and growth insights. Each reads only the fields its own
    branch needs, so a caller asking purely for a chart never has to supply
    SQL or forecast parameters.
    """

    messages: Annotated[List[Any], operator.add]
    domain_context: Optional[Literal["ecomm", "store"]]
    # SQL branch — AskData.execute_sql_query.
    query: Optional[str]
    generated_sql: Optional[str]
    query_results: Optional[List[Dict[str, Any]]]
    row_count: Optional[int]
    sql_summary: Optional[str]
    # Visualization branch — AskData.generate_visualization. `visualize`
    # controls the SQL branch's auto-chart step: None means "chart it if the
    # rows are chartable", False suppresses it outright.
    chart_type: Optional[str]
    chart_title: Optional[str]
    chart_data: Optional[Dict[str, Any]]
    visualize: Optional[bool]
    chart_spec: Optional[Dict[str, Any]]
    plotly_json: Optional[Dict[str, Any]]
    # Insights branch — AskData.simulate_and_visualize_growth.
    baseline_monthly_revenue: Optional[float]
    expected_lift_pct: Optional[float]
    lift_std_dev: Optional[float]
    growth_result: Optional[Dict[str, Any]]
    missing_inputs: Annotated[List[str], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]
