import operator
from datetime import datetime
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict

from pydantic import BaseModel, Field

# ==========================================
# 1. Enums & Literal Discriminators
# ==========================================

ExperimentStatus = Literal["DRAFT", "RUNNING", "PAUSED", "COMPLETED", "ARCHIVED"]
PhaseType = Literal["DISCOVERY", "PLANNING", "EXECUTION", "EVALUATION", "INSIGHTS"]
SRMStatusType = Literal["HEALTHY", "WARNING", "CRITICAL"]
ArtifactType = Literal[
    "stat_results_card",
    "srm_alert_card",
    "plotly_chart",
    "experiment_brief",
    "growth_prediction_card",
    "sql_result_card",
    "custom_card",
]


# ==========================================
# 2. MatchView UI Artifact Model
# ==========================================


class UIArtifact(BaseModel):
    """
    Structured visual artifact generated by tool execution and subgraphs.
    Sent over SSE to render dynamic interactive cards in MatchView workspace.
    """

    artifact_id: str = Field(..., description="Unique artifact identifier")
    type: ArtifactType = Field("stat_results_card", description="MatchView card component type")
    title: str = Field(..., description="Display title for the visual card")
    payload: Dict[str, Any] = Field(
        default_factory=dict, description="Component-specific JSON props"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(), description="Creation timestamp"
    )


# ==========================================
# 3. Card Payload Helper Schemas (Typed Component Props)
# ==========================================


class StatResultsPayload(BaseModel):
    control_mean: float
    treatment_mean: float
    relative_lift_pct: float
    p_value: float
    is_statistically_significant: bool
    confidence_interval: List[float]
    summary: str


class SRMAlertPayload(BaseModel):
    control_count: int
    treatment_count: int
    expected_ratio: float = 0.5
    p_value: float
    srm_detected: bool
    status: SRMStatusType
    summary: str


class PowerCalcPayload(BaseModel):
    sample_size_per_variant: int
    total_sample_size: int
    mde_relative: float
    baseline_rate: float
    estimated_days: int
    summary: str


class ExperimentBriefPayload(BaseModel):
    hypothesis: str
    primary_metric: str
    guardrail_metrics: List[str] = Field(default_factory=list)
    sample_size_per_variant: int
    target_lift_pct: float
    estimated_annual_impact: float


# ==========================================
# 4. Database Catalog & Introspection Models
# ==========================================


class ColumnDefinition(BaseModel):
    name: str
    data_type: str
    is_nullable: bool = True
    description: str = ""


class MetricDefinition(BaseModel):
    name: str
    table: str
    column: str
    aggregation: Literal["SUM", "AVG", "COUNT", "COUNT_DISTINCT", "MIN", "MAX"] = "AVG"
    description: str = ""


class TableSchema(BaseModel):
    table_name: str
    row_count: Optional[int] = None
    columns: List[ColumnDefinition] = Field(default_factory=list)


class SchemaMetadata(BaseModel):
    tables: List[str] = Field(default_factory=list)
    table_schemas: Dict[str, TableSchema] = Field(default_factory=dict)
    schema_summary: str = ""
    metrics_catalog: Dict[str, MetricDefinition] = Field(default_factory=dict)
    cataloged_experiments: List[Dict[str, Any]] = Field(default_factory=list)


# ==========================================
# 5. Project & Experiment Metadata Models
# ==========================================


class VariantConfig(BaseModel):
    name: str
    allocation_ratio: float = 0.5


class ExperimentSummary(BaseModel):
    project_id: str
    experiment_id: str
    name: str
    status: ExperimentStatus = "RUNNING"
    primary_metric: str
    sample_size: int = 0
    srm_status: SRMStatusType = "HEALTHY"
    table_source: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class ExperimentBrief(BaseModel):
    experiment_id: str
    hypothesis: str
    primary_metric: MetricDefinition
    guardrails: List[MetricDefinition] = Field(default_factory=list)
    target_mde: float
    baseline_rate: float
    required_sample_size: int
    traffic_split: Dict[str, float] = Field(
        default_factory=lambda: {"control": 0.5, "treatment": 0.5}
    )


# ==========================================
# 6. Tool Execution & Audit Logs
# ==========================================


class ToolExecutionRecord(BaseModel):
    tool_name: str
    input_params: Dict[str, Any]
    result: Optional[Dict[str, Any]] = None
    status: Literal["success", "failed"] = "success"
    error_message: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ==========================================
# 7. Human-in-the-Loop (HITL) Checkpoint State
# ==========================================


class PendingAction(BaseModel):
    action_type: str  # e.g., "EXECUTE_WRITE_SQL", "PUBLISH_EXPERIMENT"
    description: str
    payload: Dict[str, Any]
    requested_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ==========================================
# 8. Main AgentState & Subgraph States
# ==========================================


class AgentState(TypedDict):
    """
    Global LangGraph State container persisted across threads, tools, and HITL checkpoints.
    """

    messages: Annotated[List[Any], operator.add]
    active_project_id: Optional[str]
    active_experiment_id: Optional[str]
    thread_id: str
    active_phase: PhaseType
    schema_metadata: Optional[SchemaMetadata]
    tool_executions: Annotated[List[ToolExecutionRecord], operator.add]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]
    requires_approval: bool
    pending_action: Optional[PendingAction]


# Subgraph-Specific States


class IngestionState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    schema_metadata: Optional[SchemaMetadata]
    raw_tables_discovered: List[str]
    errors: Annotated[List[str], operator.add]


class PlanningState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: Optional[str]
    experiment_brief: Optional[ExperimentBrief]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]


class MonitoringState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: str
    srm_status: SRMStatusType
    guardrail_alerts: List[str]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]


class AnalysisState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    active_experiment_id: str
    primary_metric: str
    use_cuped: bool
    statistical_significance: Optional[bool]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]


class AskDataState(TypedDict):
    messages: Annotated[List[Any], operator.add]
    generated_sql: Optional[str]
    query_results: Optional[List[Dict[str, Any]]]
    ui_artifacts: Annotated[List[UIArtifact], operator.add]
    errors: Annotated[List[str], operator.add]
